## Text Mining - TP Stocks

### Librerias

In [50]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

### Carga de los datos

In [51]:
data = pd.read_excel('C:/Users/ferna/Downloads/ypf PAGINAS.xlsx', sheet_name= 'UNIFICADO')

In [52]:
data

Text       Date  Category  \
0    YPF Sociedad Anónima: A Speculative Trend Play... 2023-08-04  Positive   
1    YPF Sociedad: Q1 Earnings On Track, Production... 2023-05-14  Positive   
2    YPF Sociedad: Shares Still A Value, Bullish Co... 2023-03-03  Positive   
3    YPF sees continued government backing for ener... 2023-08-11  Positive   
4    Recession fears, central bank rate hikes sent ... 2023-06-23  Negative   
..                                                 ...        ...       ...   
158  YPF Sociedad Anónima (NYSE:YPF) Q4 2022 Earnin... 2023-03-13  Negative   
159  YPF Sociedad Anonima (YPF) Stock Moves -0.09%:... 2023-02-21  Negative   
160       Best Value Stocks to Buy for February 3rd —  2023-02-03  Positive   
161  YPF Sociedad Anonima (YPF) Moves 7.1% Higher: ... 2023-01-16  Positive   
162  The Top 5 Exploration Prospects of 2023 — 2022... 2023-01-06  Positive   

    Train/Test                                             Pagina  
0         Test                               www.seekingalpha.com  
1        Train                               www.seekingalpha.com  
2        Train                               www.seekingalpha.com  
3         Test                               www.seekingalpha.com  
4        Train                               www.seekingalpha.com  
..         ...                                                ...  
158      Train  https://finance.yahoo.com/news/ypf-sociedad-ni...  
159      Train  https://finance.yahoo.com/news/ypf-sociedad-an...  
160      Train  https://finance.yahoo.com/news/best-value-stoc...  
161      Train  https://finance.yahoo.com/news/ypf-sociedad-an...  
162      Train  https://oilprice.com/Energy/Crude-Oil/The-Top-...  

[163 rows x 5 columns]

### Train / Test

In [53]:
data_train = data[data['Train/Test'].isin(['Train'])]
data_test = data[data['Train/Test'].isin(['Test'])]

In [54]:
X_train = data_train['Text'].tolist()
y_train = data_train['Category'].tolist()

In [55]:
X_test = data_test['Text'].tolist()
y_test = data_test['Category'].tolist()

### Naive Bayes Multinomial

In [56]:
# Stemming / Lemma / stopwords
# clf: logistica / SVM / Random Forest //// BERT

text_clf_nb = Pipeline([('vect' , CountVectorizer()), 
                     ('tfidf', TfidfTransformer()), 
                     ('clf'  , MultinomialNB())
                    ])

In [57]:
from sklearn.multiclass import OneVsRestClassifier

text_clf_nb2 = Pipeline([('vect' , CountVectorizer()), 
                     ('tfidf', TfidfTransformer()), 
                     ('clf'  , OneVsRestClassifier(MultinomialNB(fit_prior=True, class_prior=None)))
                    ])

### Entrenamiento

In [58]:
text_clf_nb = text_clf_nb.fit(X_train, y_train)

text_clf_nb2 = text_clf_nb2.fit(X_train, y_train)

### Testeo

In [59]:
y_pred_nb = text_clf_nb.predict(X_test)

y_pred_nb2 = text_clf_nb2.predict(X_test)

### Score Naive Bayes

In [60]:
text_clf_nb.score(X_train, y_train)

text_clf_nb2.score(X_train, y_train)

0.8421052631578947

In [61]:
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_nb) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_nb, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))

Accuracy: 63.33%

F1 Score: 49.12

Confusion Matrix:
 [[ 0  0  3]
 [ 0  0  8]
 [ 0  0 19]]


In [62]:
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_nb2) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_nb2, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_nb2))

Accuracy: 63.33%

F1 Score: 49.12

Confusion Matrix:
 [[ 0  0  3]
 [ 0  0  8]
 [ 0  0 19]]


### Support Vector Classifier

In [63]:
from sklearn.svm import LinearSVC

In [64]:
text_clf_svc = Pipeline([('vect' , CountVectorizer()), 
                     ('tfidf', TfidfTransformer()), 
                     ('clf'  , LinearSVC())
                    ])

text_clf_svc2 = Pipeline([('vect' , CountVectorizer()), 
                     ('tfidf', TfidfTransformer()), 
                     ('clf'  ,  OneVsRestClassifier(LinearSVC(), n_jobs=1))
                    ])

In [65]:
text_clf_svc = text_clf_svc.fit(X_train, y_train)

text_clf_svc2 = text_clf_svc2.fit(X_train, y_train)

In [66]:
y_pred_svc = text_clf_svc.predict(X_test)

y_pred_svc2 = text_clf_svc2.predict(X_test)

In [67]:
text_clf_svc.score(X_train, y_train)

text_clf_svc2.score(X_train, y_train)

0.9924812030075187

In [68]:
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_svc) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_svc, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_svc))

Accuracy: 66.67%

F1 Score: 64.44

Confusion Matrix:
 [[ 1  0  2]
 [ 2  2  4]
 [ 2  0 17]]


In [69]:
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_svc2) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_svc2, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_svc2))

Accuracy: 66.67%

F1 Score: 64.44

Confusion Matrix:
 [[ 1  0  2]
 [ 2  2  4]
 [ 2  0 17]]


### Random Forest

In [70]:
from sklearn.ensemble import RandomForestClassifier

In [71]:
text_clf_rf = Pipeline([
    ('vect' , CountVectorizer()), 
    ('tfidf', TfidfTransformer()), 
    ('clf'  , RandomForestClassifier())
])

In [72]:
text_clf_rf = text_clf_rf.fit(X_train, y_train)

In [73]:
y_pred_rf = text_clf_rf.predict(X_test)

In [74]:
text_clf_rf.score(X_train, y_train)

1.0

In [75]:
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_rf) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_rf, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

Accuracy: 66.67%

F1 Score: 60.23

Confusion Matrix:
 [[ 0  0  3]
 [ 0  2  6]
 [ 1  0 18]]


### Ensamble?

In [76]:
models_pred = pd.DataFrame(
    {
        'X_test': X_test,
        'y_test': y_test,
        'MultinomialNB': y_pred_nb,
        'SVC': y_pred_svc,
        'RandomForest': y_pred_rf,
        'Word2Vec': y_pred_w2v
    }
)

In [77]:
models_pred

X_test    y_test MultinomialNB  \
0   YPF Sociedad Anónima: A Speculative Trend Play...  Positive      Positive   
1   YPF sees continued government backing for ener...  Positive      Positive   
2   Is YPF SA (YPF) a Smart Choice in Oil & Gas In...   Neutral      Positive   
3   Summary. The company has strong fundamentals. ...  Positive      Positive   
4   Argentina Fixes Oil at $56 a Barrel to Put Lid...  Negative      Positive   
5   Presidential Front-Runner Would Unshackle Arge...   Neutral      Positive   
6   Free Marketeer Leading Election Would Rock Arg...   Neutral      Positive   
7   Argentine Election Won’t Derail Shale Growth, ...  Positive      Positive   
8   Here Are Argentina’s Assets to Watch Before Ke...   Neutral      Positive   
9   Argentina’s Dollar Fever Sparks $1.4 Billion I...  Negative      Positive   
10  An Oil Boom Could Deliver Argentina from Econo...  Positive      Positive   
11  China’s Zijin Is in Talks With Argentina to Tu...  Positive      Positive   
12  Argentina’s Pan American Energy Joins Oil Indu...  Positive      Positive   
13  Argentina hits milestone on path to gas export...  Positive      Positive   
14  Argentina’s Milei aims to balance budget withi...  Positive      Positive   
15  Argentina’s far-right libertarian wants toughe...  Positive      Positive   
16   \nYPF Sociedad Anonima (YPF) Outpaces Stock M...  Positive      Positive   
17   \nYPF Sociedad Anonima (YPF) Gains As Market ...  Positive      Positive   
18   \nZacks Investment Ideas feature highlights: ...  Positive      Positive   
19  YPF call volume above normal and directionally...  Positive      Positive   
20      YPF Upcoming Earnings Report: What to Expect?   Neutral      Positive   
21  Mexico's Pemex the biggest liquidity worry amo...   Neutral      Positive   
22  Argentina to freeze crude price at $56/bbl to ...  Negative      Positive   
23  YPF expects Argentina to maintain support for ...  Positive      Positive   
24  Key pipeline needs investment to deliver Argen...  Positive      Positive   
25  Vaca Muerta's Sweet Crude Attracts Global Ener...  Positive      Positive   
26  YPF Sociedad Anonima (YPF) Outpaces Stock Mark...   Neutral      Positive   
27      14 Best Multibagger Stocks to Buy for 2024 —   Positive      Positive   
28  YPF Sociedad Anonima (YPF) Gains As Market Dip...   Neutral      Positive   
29  Will Argentina Reach Its 1 Million Bpd Oil Pro...  Positive      Positive   

         SVC RandomForest  Word2Vec  
0   Positive     Positive  Positive  
1   Positive     Positive  Positive  
2   Positive     Positive   Neutral  
3   Positive     Positive  Positive  
4   Positive     Positive  Positive  
5   Negative     Positive  Positive  
6   Negative     Positive  Positive  
7   Positive     Positive   Neutral  
8   Positive     Positive  Positive  
9   Negative     Positive  Positive  
10  Positive     Positive  Positive  
11  Positive     Positive  Positive  
12  Positive     Positive  Positive  
13  Positive     Positive   Neutral  
14  Positive     Positive  Positive  
15  Positive     Positive  Negative  
16  Positive     Positive  Positive  
17  Positive     Negative  Positive  
18  Positive     Positive  Positive  
19  Negative     Positive  Positive  
20  Positive     Positive  Positive  
21  Positive     Positive  Positive  
22  Positive     Positive  Positive  
23  Negative     Positive  Positive  
24  Positive     Positive  Negative  
25  Positive     Positive  Positive  
26   Neutral      Neutral   Neutral  
27  Positive     Positive  Positive  
28   Neutral      Neutral   Neutral  
29  Positive     Positive   Neutral

In [73]:
models_pred.to_excel('ypf_predictions_results.xlsx', index=False)

## Balanceo de Clases

In [59]:
data.Category.value_counts()

Positive    87
Neutral     49
Negative    27
Name: Category, dtype: int64

## Word2Vec

In [18]:
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [25]:
import gensim

In [33]:
dataset = data[['Text','Train/Test','Category']]

In [34]:
dataset['text_clean'] = dataset['Text'].apply(lambda x: gensim.utils.simple_preprocess(x))
dataset.head()

C:\Users\ferna\AppData\Local\Temp\ipykernel_8092\4001183646.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['text_clean'] = dataset['Text'].apply(lambda x: gensim.utils.simple_preprocess(x))


Text Train/Test  Category  \
0  YPF Sociedad Anónima: A Speculative Trend Play...       Test  Positive   
1  YPF Sociedad: Q1 Earnings On Track, Production...      Train  Positive   
2  YPF Sociedad: Shares Still A Value, Bullish Co...      Train  Positive   
3  YPF sees continued government backing for ener...       Test  Positive   
4  Recession fears, central bank rate hikes sent ...      Train  Negative   

                                          text_clean  
0  [ypf, sociedad, anónima, speculative, trend, p...  
1  [ypf, sociedad, earnings, on, track, productio...  
2  [ypf, sociedad, shares, still, value, bullish,...  
3  [ypf, sees, continued, government, backing, fo...  
4  [recession, fears, central, bank, rate, hikes,...

In [35]:
dataset_train = dataset[dataset['Train/Test'].isin(['Train'])]
dataset_test = dataset[dataset['Train/Test'].isin(['Test'])]

In [36]:
X_train = dataset_train['Text'].tolist()
y_train = dataset_train['Category'].tolist()

X_test = dataset_test['Text'].tolist()
y_test = dataset_test['Category'].tolist()

In [37]:
w2v_model = gensim.models.Word2Vec(X_train,
                                   vector_size=100,
                                   window=5,
                                   min_count=2)

In [40]:
import numpy as np

words = set( w2v_model.wv.index_to_key )

X_train_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])
                         for ls in X_train])

X_test_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])
                         for ls in X_test])

C:\Users\ferna\AppData\Local\Temp\ipykernel_8092\3952047339.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_train_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])
C:\Users\ferna\AppData\Local\Temp\ipykernel_8092\3952047339.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_test_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])


In [41]:
X_train_vect_avg = []
for v in X_train_vect:
    if v.size:
        X_train_vect_avg.append(v.mean(axis=0))
    else:
        X_train_vect_avg.append(np.zeros(100, dtype=float))
        
X_test_vect_avg = []
for v in X_test_vect:
    if v.size:
        X_test_vect_avg.append(v.mean(axis=0))
    else:
        X_test_vect_avg.append(np.zeros(100, dtype=float))

In [45]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf_model = rf.fit(X_train_vect_avg, y_train)

In [48]:
y_pred_w2v = rf_model.predict(X_test_vect_avg)

In [78]:
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred_w2v) * 100))
print("\nF1 Score: {:.2f}".format(f1_score(y_test, y_pred_w2v, average='weighted') * 100))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_w2v))

Accuracy: 56.67%

F1 Score: 54.68

Confusion Matrix:
 [[ 0  0  3]
 [ 0  3  5]
 [ 2  3 14]]


### BERT

In [29]:
from transformers import BertTokenizer, BertForSequenceClassification

model_name = "bert-base-uncased"
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=3)
tokenizer = BertTokenizer.from_pretrained(model_name)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [30]:
# Tokenize and encode text
encoded_data = tokenizer(X_train, padding='max_length', truncation=True, return_tensors='pt', max_length=128)

input_ids = encoded_data['input_ids']
attention_mask = encoded_data['attention_mask']

In [32]:
with torch.no_grad():
    outputs = model(input_ids, attention_mask=attention_mask)

predictions = outputs.logits.argmax(dim=1).tolist()

In [ ]:
results = {'Text': X_train, 'True Label': y_train, 'Predicted Label': predictions}
results_df = pd.DataFrame(results)

output_file = "predictions.xlsx"
results_df.to_excel(output_file, index=False)

In [ ]:
word_counts = {}

for sentence in data[data['Category'].isin(['Positive'])]['Text'].to_list():
    words = sentence.split()
    
    for word in words:
        word = word.strip(".,!?()").lower()
        
        if word in word_counts:
            word_counts[word] += 1
        else:
            word_counts[word] = 1

In [ ]:
dict(sorted(word_counts.items(), key=lambda x: x[1], reverse=True))